name: 'Check Licenses'
description: 'Checks your NPM Licenses'
inputs:
  project-root:
    description: 'Root of the project, relative to the cwd'
    required: false
    default: '.'
runs:
  using: 'node16'
  main: 'index.js'
branding:
  color: purple
  icon: file-text
author: YieldingCoder
